# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Scrag End
email: bjorn@scragend.com
description: >- # this means to ignore newlines until "baseurl:"
  A journal about food, and also a cut of lamb
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://scragend.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: scrag_end
github_username:  bjornrust

# Build settings
markdown: kramdown
# theme: minima
plugins:
#  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# imported from old config file

# sass:
#   sass_dir: /css

collections:
  stories:
    output: true
    permalink: /stories/:path/

categories: [story]

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  # - assets

# Settings for Contentful
contentful:
  spaces:
    - stories:
        space: kkzerdgg97de
        access_token: cd55de6ca9112c2ffbafe03d56b6119d26d0377c03b662918708532c16ad1c04


# Settings for Data Page Generator
page_gen:
  - index_files: true #<<true or false>
    data: contentful.spaces.stories.postContainer #<<name of the data>>
    template: stories #<<name of the template to use to generate the page>>
    name: title #<<field used to generate the filename>>
    dir: stories #<<directory in which files are to be generated>>
    extension: html #<<extension used to generate the filename>>
#    filter: #<<property to filter data records by>>
#  - ...